release:
  draft: false
  prerelease: auto
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: starboard-operator
    main: ./cmd/starboard-operator/main.go
    binary: starboard-operator
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
    goarm:
      - "7"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - starboard
    replacements:
      amd64: x86_64
      arm: ARM
      arm64: ARM64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
dockers:
  - image_templates:
      - "docker.io/aquasec/starboard-operator:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    dockerfile: build/starboard-operator/Dockerfile
    goarch: amd64
    ids:
      - starboard-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=starboard-operator"
      - "--label=org.opencontainers.image.description=Keeps Starboard resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/amd64"
  - image_templates:
      - "docker.io/aquasec/starboard-operator:{{ .Version }}-ubi8-amd64"
    use: buildx
    goos: linux
    dockerfile: build/starboard-operator/Dockerfile.ubi8
    goarch: amd64
    ids:
      - starboard-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=starboard-operator"
      - "--label=org.opencontainers.image.description=Keeps Starboard resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/amd64"
  - image_templates:
      - "docker.io/aquasec/starboard-operator:{{ .Version }}-arm64"
    use: buildx
    goos: linux
    dockerfile: build/starboard-operator/Dockerfile
    goarch: arm64
    ids:
      - starboard-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=starboard-operator"
      - "--label=org.opencontainers.image.description=Keeps Starboard resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/arm64"
  - image_templates:
      - "docker.io/aquasec/starboard-operator:{{ .Version }}-ubi8-arm64"
    use: buildx
    goos: linux
    dockerfile: build/starboard-operator/Dockerfile.ubi8
    goarch: arm64
    ids:
      - starboard-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=starboard-operator"
      - "--label=org.opencontainers.image.description=Keeps Starboard resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/arm64"
  - image_templates:
      - "docker.io/aquasec/starboard-operator:{{ .Version }}-s390x"
    use: buildx
    goos: linux
    dockerfile: build/starboard-operator/Dockerfile
    goarch: s390x
    ids:
      - starboard-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=starboard-operator"
      - "--label=org.opencontainers.image.description=Keeps Starboard resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/s390x"
  - image_templates:
      - "docker.io/aquasec/starboard-operator:{{ .Version }}-ppc64le"
    use: buildx
    goos: linux
    dockerfile: build/starboard-operator/Dockerfile
    goarch: ppc64le
    ids:
      - starboard-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=starboard-operator"
      - "--label=org.opencontainers.image.description=Keeps Starboard resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/ppc64le"
  - image_templates:
      - "docker.io/aquasec/starboard-operator:{{ .Version }}-ubi8-s390x"
    use: buildx
    goos: linux
    dockerfile: build/starboard-operator/Dockerfile.ubi8
    goarch: s390x
    ids:
      - starboard-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=starboard-operator"
      - "--label=org.opencontainers.image.description=Keeps Starboard resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/s390x"
  - image_templates:
      - "docker.io/aquasec/starboard-operator:{{ .Version }}-ubi8-ppc64le"
    use: buildx
    goos: linux
    dockerfile: build/starboard-operator/Dockerfile.ubi8
    goarch: ppc64le
    ids:
      - starboard-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=starboard-operator"
      - "--label=org.opencontainers.image.description=Keeps Starboard resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/starboard"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/starboard/v{{ .Version }}/"
      - "--platform=linux/ppc64le"
docker_manifests:
  - name_template: "aquasec/starboard-operator:{{ .Version }}"
    image_templates:
      - "aquasec/starboard-operator:{{ .Version }}-amd64"
      - "aquasec/starboard-operator:{{ .Version }}-arm64"
      - "aquasec/starboard-operator:{{ .Version }}-s390x"
      - "aquasec/starboard-operator:{{ .Version }}-ppc64le"
  - name_template: "aquasec/starboard-operator:{{ .Version }}-ubi8"
    image_templates:
      - "aquasec/starboard-operator:{{ .Version }}-ubi8-amd64"
      - "aquasec/starboard-operator:{{ .Version }}-ubi8-arm64"
      - "aquasec/starboard-operator:{{ .Version }}-ubi8-s390x"
      - "aquasec/starboard-operator:{{ .Version }}-ubi8-ppc64le"
