site_name: The Kubernetes Security Manager
site_url: https://danielpacak.github.io/kube-security-manager/
site_description: Kubernetes-native security toolkit
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/danielpacak/kube-security-manager
edit_uri: ""

nav:
  - Introduction: index.md
  - Starboard Operator:
      - Overview: operator/index.md
      - Installation:
          - kubectl: operator/installation/kubectl.md
          - Helm: operator/installation/helm.md
          - Operator Lifecycle Manager: operator/installation/olm.md
          - Upgrade: operator/installation/upgrade.md
      - Getting Started: operator/getting-started.md
      - Configuration: operator/configuration.md
      - Troubleshooting: operator/troubleshooting.md
  - Settings: settings.md
  - Vulnerability Scanning:
      - Overview: vulnerability-scanning/index.md
      - Trivy Scanner: vulnerability-scanning/trivy.md
      - Aqua Enterprise Scanner: vulnerability-scanning/aqua-enterprise.md
      - Private Registries: vulnerability-scanning/private-registries.md
      - Managed Registries: vulnerability-scanning/managed-registries.md
  - Configuration Auditing:
      - Overview: configuration-auditing/index.md
      - Built-in Configuration Audit Policies: configuration-auditing/built-in-policies.md
      - Infrastructure Scanners:
          - Overview: configuration-auditing/infrastructure-scanners/index.md
  - Tutorials:
      - Writing Custom Configuration Audit Policies: tutorials/writing-custom-configuration-audit-policies.md
      - Manage Access to Security Reports: tutorials/manage_access_to_security_reports.md
  - Custom Resource Definitions:
      - Overview: crds/index.md
      - VulnerabilityReport: crds/vulnerability-report.md
      - ClusterVulnerabilityReport: crds/clustervulnerability-report.md
      - ConfigAuditReport: crds/configaudit-report.md
      - ClusterConfigAuditReport: crds/clusterconfigaudit-report.md
      - CISKubeBenchReport: crds/ciskubebench-report.md
      - KubeHunterReport: crds/kubehunter-report.md
  - Frequently Asked Questions: faq.md
  - Further Reading: further-reading.md

theme:
  name: material
  custom_dir: overrides
  language: 'en'
  logo: images/starboard-icon-white.svg

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

# All data defined under extra is automatically exposed as a variable and can
# be used from the template. For example, {{ var.version }}.
#
# Requires pip install mike and pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
extra:
  generator: false
  version:
    provider: mike
  var:
    prev_git_tag: "v0.15.5"
    chart_version: 0.10.6

# Requires pip install mkdocs-macros-plugin
plugins:
  - search
  - macros
