---
# This is a manually triggered workflow to build and publish documentation pages
# from the specified Git revision to GitHub pages on
# https://danielpacak.github.io/kube-security-manager/.
name: Publish documentation

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to deploy, e.g. v0.0.1
        required: true
        default: main

# Disable permissions granted to the GITHUB_TOKEN for all the available scopes.
permissions: { }

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material
          pip install mkdocs-macros-plugin
      - run: |
          git config user.name "danielpacak"
          git config user.email "pacak.daniel@gmail.com"
      - run: |
          mkdocs gh-deploy --force
